version: '3'

services:

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pseudomat
      - POSTGRES_USER=pseudomat
      - POSTGRES_PASSWORD=pseudomat

  pseudomatd:
    build: .
    links:
      - database:database
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
