---
"$schema": https://json-schema.org/draft-07/schema#
type: object
required:
  - logging
  - postgres
  - pseudomat
additionalProperties: false


properties:

  logging:
    "$ref": "#/definitions/logging.dictconfig"

  postgres:
    type: object
    additionalProperties: false
    required:
      - host
      - port
      - user
      - password
      - dbname
    properties:
      host:
        type: string
      port:
        type: integer
      user:
        type: string
      password:
        type: string
      dbname:
        type: string

  pseudomat:
    type: object
    additionalProperties: false
    required:
      - bind_port
      - secret
    properties:
      bind_port:
        type: integer
      secret:
        type: string

  sendgrid:
    type: object
    additionalProperties: false
    required:
      - url
      - api_key
    properties:
      url:
        type: string
        format: url
      api_key:
        type: string

  sqlite:
    type: object
    additionalProperties: false
    required:
      - filename
    properties:
      filename:
        type: string


definitions:
  logging.dictconfig:
    type: object
    additionalProperties: false
    required:
      - version
    properties:
      version:
        type: integer
        enum:
          - 1
      formatters:
        type: object
        patternProperties:
          "^[a-zA-Z0-9._-]+$":
            type: object
            properties:
              format:
                type: string
              datefmt:
                type: string
            additionalProperties: false
      filters:
        type: object
        patternProperties:
          "^[a-zA-Z0-9._-]+$":
            type: object
            properties:
              name:
                type: string
            additionalProperties: false
      handlers:
        type: object
        patternProperties:
          "^[a-zA-Z0-9._-]+$":
            type: object
            required:
              - class
            properties:
              class:
                type: string
              level:
                type: string
                enum:
                  - CRITICAL
                  - ERROR
                  - WARNING
                  - INFO
                  - DEBUG
              formatter:
                type: string
              filters:
                type: array
                items:
                  type: string
                uniqueItems: true
      loggers:
        type: object
        patternProperties:
          "^[a-zA-Z0-9._-]+$":
            type: object
            properties:
              level:
                type: string
                enum:
                  - CRITICAL
                  - ERROR
                  - WARNING
                  - INFO
                  - DEBUG
              propagate:
                type: boolean
              filters:
                type: array
                items:
                  type: string
                uniqueItems: true
              handlers:
                type: array
                items:
                  type: string
                uniqueItems: true
      root:
        type: object
        properties:
          level:
            type: string
            enum:
              - CRITICAL
              - ERROR
              - WARNING
              - INFO
              - DEBUG
          filters:
            type: array
            items:
              type: string
            uniqueItems: true
          handlers:
            type: array
            items:
              type: string
            uniqueItems: true
      incremental:
        type: boolean
      disable_existing_loggers:
        type: boolean
